package cc.twittertools.words.dict;

import java.io.BufferedWriter;
import java.io.IOException;

import org.apache.commons.lang3.tuple.Pair;

import com.twitter.common.text.token.attribute.TokenType;

public class NullTokenDictionary implements TokenDictionary {

	public static final String IDENTIFIER = "__null_dict";

	public NullTokenDictionary() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public int toInt(String word) {
		return IGNORABLE_WORD;
	}

	@Override
	public String toWord(int wordId) {
		throw new IllegalStateException ("Null dictionaries do not provide IDs for words, so the given ID cannot have been generated by this dictionary");
	}

	@Override
	public void seal() {
		;
	}

	@Override
	public int size() {
		return 0;
	}

	@Override
	public int capacity() {
		return 0;
	}

	@Override
	public void writeAsPythonList(String pyVarName, BufferedWriter writer)
			throws IOException {
		writer.write (pyVarName + " = [ ]\n");
	}

	@Override
	public int toInt(TokenType tokenType, String word) {
		return IGNORABLE_WORD;
	}

	@Override
	public Pair<TokenType, String> toWordToken(int wordId) {
		throw new IllegalStateException ("Null dictionaries do not provide IDs for words, so the given ID cannot have been generated by this dictionary");
	}

	@Override
	public int size(TokenType tokenType) {
		return 0;
	}

	@Override
	public int capacity(TokenType tokenType) {
		return 0;
	}
	
	@Override
	public NullTokenDictionary clone() {
		return this; // this is a threadsafe, stateless singleton class.
	}
}
